### ISSUE TITLE
Feature parity with jest-serializer-vue-tjw

### ISSUE THREAD

**Issue by TheJaredWilcurt** [eddyerburgh/jest-serializer-vue#31]
Since forking `jest-serializer-vue` I've essentially rewrote the entire repo. This includes changing things like the CI, and code style, with very different linting settings. I've also restructured the files. Making a direct PR against this repo would likely be undesired by the maintainer. However, unless the Vue core team wants to adopt my version, the majority of people using Vue will automatically inherit this version. I'd like to see this version improved to include the same features I've already implemented in my fork.

* https://github.com/tjw-lint/jest-serializer-vue-tjw 

**Feature Parity Tracker:**

* [ ] Settings API so users can tweak any setting
* [x] Remove `data-server-rendered`
* [x] Remove `data-test` #16 
* [ ] Remove `data-test-id`
* [ ] Remove `data-testid`
* [ ] Remove `data-qa` (disabled by default)
* [ ] Remove `data-v` ID's
* [ ] Remove all HTML comments (disabled by default)
* [ ] Expose "pretty" settings, change defaults to look better #13 
* [ ] Show JSON data in HTML attributes instead of `[object Object]` #17
